Repository ceadoor/cea.ac.in, pull requests merged in 2018-10, with the labels that each got.

#64 added content course1-page
  src/contact.html
  src/sass/admin.scss
  src/sass/components.scss
  src/sass/contact-Us.scss
  src/sass/innovation.scss
  src/sass/studies-01.scss
  src/studies/btech-computer-science-engg.html
Labels: enhancement

#125 center aligned
  README.md
Labels: Priority: low

#127 Creating the page our history with a timeline
  package-lock.json
  src/about/our-history.html
  src/index.html
  src/sass/main.scss
  src/sass/our-history.scss
  webpack.config.js
Labels: enhancement

#135 Added the files and included
  src/news.html
  webpack.config.js
Labels: tuning needed

#207 Update src/gallery.html
  src/gallery.html
Labels: tuning needed
